main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("accounts/signup/", views.signup, name="signup"),
    path("horses/", views.HorseList.as_view(), name="horses_index"),
    path("horses/<int:horse_id>/", views.horses_detail, name="detail"),
    path("horses/<int:horse_id>/add_horse_outcome/", views.add_horse_outcome, name="add_horse_outcome"),
    path("horses/<int:pk>/delete", views.HorseDelete.as_view(), name="horses_delete"),
    path("delete_horse_outcome/<int:outcome_id>/", views.delete_horse_outcome, name="delete_horse_outcome"),
    path("jockeys/<int:jockey_id>/assoc_horse/<int:horse_id>/", views.assoc_horse, name="assoc_horse"
    ),
    path("jockeys/<int:jockey_id>/", views.jockeys_detail, name="jdetail"),
    path("jockeys/<int:pk>/delete", views.JockeyDelete.as_view(), name="jockeys_delete"),
    path("jockeys/<int:jockey_id>/unassoc_horse/<int:horse_id>/", views.unassoc_horse, name="unassoc_horse"),
    path("jockeys/", views.JockeyList.as_view(), name="jockeys_index"),
   
    path('jockeys/<int:jockey_id>/add_jockey_experience/', views.add_jockey_experience, name="add_jockey_experience"),
    path("delete_jockey_experience/<int:experience_id>/", views.delete_jockey_experience, name="delete_jockey_experience"),
    path("horses/create/", views.HorseCreate.as_view(), name="horses_create"),
    path("jockeys/create/", views.JockeyCreate.as_view(), name="jockeys_create"),
    path("horses/<int:pk>/update", views.HorseUpdate.as_view(), name="horses_update"),
    path("jockeys/<int:pk>/update", views.JockeyUpdate.as_view(), name="jockeys_update"),
]

offthepace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

RACE_OUTCOMES = [
    ("W", "Win"),
    ("P", "Place"),
    ("S", "Show"),
    ("U", "Unplaced")
]

RACE_GRADES = [
    ("G1", "GRADE ONE"),
    ("G2", "GRADE TWO"),
    ("G3", "GRADE THREE"),
]


# class Race(models.Model):
#     name = models.CharField(max_length=200)
#     host_track = models.CharField(max_length=200)
#     city = models.CharField(max_length=200)
#     field_size = models.IntegerField()
#     grade = models.CharField(max_length=2, choices=RACE_GRADES)
#     distance = models.CharField(max_length=200)
#     race_date = models.DateField()
#     entries = models.TextField(max_length=500)

#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return reverse('detail', kwargs={'race_id' : self.id})


class Horse(models.Model):
    name = models.CharField(max_length=150)
    age = models.IntegerField()
    starts = models.IntegerField()
    sire = models.CharField(max_length=150)
    dam = models.CharField(max_length=150)
    description = models.TextField(max_length=250)
    trainer = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"horse_id": self.id})



class Jockey(models.Model):
    name = models.CharField(max_length=150)
    starts = models.IntegerField()
    age = models.IntegerField()
    bio = models.TextField(max_length=500, default="")
    horses = models.ManyToManyField(Horse)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("jdetail", kwargs={"jockey_id": self.id})

    def most_recent_run(self):
        return self.outcome_set.filter(date=date.today()).count() >= len(RACE_OUTCOMES)


class Outcome(models.Model):
    name = models.CharField(max_length=150, default="Race Title")
    date = models.DateField("Date")
    outcome = models.CharField(
        max_length=1,
        choices=RACE_OUTCOMES,
        default=RACE_OUTCOMES[0][0],
    )

    horse = models.ForeignKey(Horse, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_outcome_display()} on {self.date}"

    def get_absolute_url(self):
        return reverse("horses/detail", kwargs={"pk": self.id})    
    class Meta:
        ordering = ["-date"]

class Experience(models.Model):
    name = models.CharField(max_length=150, default="Race Title")
    date = models.DateField("Date")
    experience = models.CharField(
        max_length=1,
        choices=RACE_OUTCOMES,
        default=RACE_OUTCOMES[0][0],
    )

    jockey = models.ForeignKey(Jockey, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_experience_display()} on {self.date}"

    def get_absolute_url(self):
        return reverse("jockeys/detail.html", kwargs={"pk": self.id})    

    # change the default sort
    class Meta:
        ordering = ["-date"]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="", blank=True)

    def __str__(self):
        return f"{self.user.username} Profile"

main_app/forms.py
from django.forms import ModelForm
from .models import Outcome, Experience
from django.contrib.auth.models import User
 

class OutcomeForm(ModelForm):
    class Meta:
        model = Outcome
        fields = ['name', 'date', 'outcome']


class ExperienceForm(ModelForm):
    class Meta:
        model = Experience
        fields = ['name', 'date', 'experience']        

# class ProfileForm(ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['username', 'password', 'firstname', 'lastname']        

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Horse, Jockey, Outcome, Profile, Experience
from .forms import OutcomeForm, ExperienceForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def home(request):
    return render(request, 'home.html')

   
class HorseList(LoginRequiredMixin, ListView):
    model = Horse
    
    def get_queryset(self):
        return Horse.objects.filter(user=self.request.user)

@login_required
def horses_detail(request, horse_id):
    horse = Horse.objects.get(id=horse_id)
    outcome_form = OutcomeForm()
    return render(request, 'horses/detail.html', {'horse' : horse, 'outcome_form': outcome_form})

@login_required
def add_horse_outcome(request, horse_id):
    form = OutcomeForm(request.POST)
    if form.is_valid():
        new_outcome = form.save(commit=False)
        new_outcome.horse_id = horse_id
        new_outcome.save()
    return redirect('detail', horse_id=horse_id)    

@login_required
def delete_horse_outcome(request, outcome_id):
    Outcome.objects.filter(id = outcome_id).delete()
    return redirect('/horses/')   

@login_required
def assoc_horse(request, jockey_id, horse_id):
    Jockey.objects.get(id=jockey_id).horses.add(horse_id)
    return redirect('jdetail', jockey_id=jockey_id)

@login_required
def unassoc_horse(request, jockey_id, horse_id):
    Jockey.objects.get(id=jockey_id).horses.remove(horse_id)
    return redirect('jdetail', jockey_id=jockey_id)    

class HorseCreate(LoginRequiredMixin, CreateView):
    model = Horse
    fields = ['name', 'age', 'description', 'starts', 'trainer', 'sire', 'dam']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)    

class HorseUpdate(LoginRequiredMixin, UpdateView):
    model = Horse
    fields = ['name', 'age', 'description', 'starts', 'trainer', 'sire', 'dam']

class HorseDelete(LoginRequiredMixin, DeleteView):
    model = Horse
    success_url = '/horses/'

class JockeyList(LoginRequiredMixin, ListView):
    model = Jockey
    
    def get_queryset(self):
        return Jockey.objects.filter(user=self.request.user)

@login_required
def jockeys_detail(request, jockey_id):
    jockey = Jockey.objects.get(id=jockey_id)
    not_ridden = Horse.objects.exclude(id__in = jockey.horses.all().values_list('id'))
    experience_form=ExperienceForm()
    return render(request, 'jockeys/jdetail.html', {'jockey' : jockey, 'experience_form': experience_form, 'horses' : not_ridden})

@login_required
def add_jockey_experience(request, jockey_id):
    form= ExperienceForm(request.POST)
    if form.is_valid():
        j_experience = form.save(commit=False)
        j_experience.jockey_id = jockey_id
        j_experience.save()
    return redirect('jdetail', jockey_id=jockey_id)     

@login_required
def delete_jockey_experience(request, experience_id):
    Experience.objects.filter(id = experience_id).delete()
    return redirect('/jockeys/')

class JockeyCreate(LoginRequiredMixin, CreateView):
    model = Jockey
    fields = ['age', 'name', 'bio', 'starts']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)    

class JockeyUpdate(LoginRequiredMixin, UpdateView):
    model = Jockey
    fields = ['age', 'bio', 'starts']

class JockeyDelete(LoginRequiredMixin, DeleteView):
    model = Jockey
    success_url = '/jockeys/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('/')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/jockeys/jdetail.html
{% extends 'base.html' %}
{% block content %}


<h1 class="mx-5 my-5" >Jockey Details</h1> 
<hr></hr>
<container id='horse-details-container'>
  <div class="card w-50 mx-5 my-5 border-secondary shadow">
    <h5 class="card-header bg-success bg-gradient">{{jockey.name}}</h5>
    <div class="card-body " style="background-color: #f6f6f6">
      <h5 class="card-title">Age: {{jockey.age}}</h5>
      <p class="card-text">Number of Races: {{jockey.starts}}</p>
      <p class="card-text">Bio: {{jockey.bio}}</p>
      <a href="{% url 'jockeys_update' jockey.id %}" class="btn btn-outline-success">Update</a>
      <a href="{% url 'jockeys_delete' jockey.id %}" class="btn btn-outline-success">Delete</a>
    </div>
  </div>
</container>
<hr></hr>
<h5 class="mx-5 mt-5">Race History</h5> 
<div class="mx-5 my-5">
  <form action="{% url 'add_jockey_experience' jockey.id %}" method="post">
    {% csrf_token %}
    {{ experience_form.as_p }}
    <input type="submit" class="btn btn-outline-success" value="Add Race Result">
  </form>
</div>  

<h5 class="mx-5 mt-5">Results</h5> 
<table class="table w-75 mx-5 my-5">
  <thead>
    <tr><th scope="col">Race</th><th scope="col">Date</th><th scope="col">Result</th></tr>
  </thead>
  <tbody>
    {% for experience in jockey.experience_set.all %}
      <tr>
        <td scope="row">{{experience.name}}</td>
        <td scope="row">{{experience.date}}</td>
        <td scope="row">{{experience.get_experience_display}}</td>
        <td scope="row">
          <form action="{% url 'delete_jockey_experience' experience.id %}" method="delete">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-success" value="Delete Race">
          </form>
        </td>  
      </tr>  
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<hr></hr>

<div class="container">
  <div class="row">
    <div class="col-md">
      <h3 class="mx-3 my-3">{{ jockey.name }}'s Rides</h3>
        {% if jockey.horses.count %}
          {% for horse in jockey.horses.all %}
            <div class="card w-50 mx-2 my-3 shadow " style="background-color: #f6f6f6">
              <div class="card-content mx-2 my-3" >
                <span class="card-title bg-success">
                  <p> {{ horse.name }} <p>
                  <form action="{% url 'unassoc_horse' jockey.id horse.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-outline-success" value="Remove">
                  </form>
                </span>
              </div>
            </div>        
      {% endfor %}
    {% else %}  
      <h5 class="mx-3 my-3">No Horses Added!</h5>
    {% endif %}
    </div>
  </div>
  <!-- Available toys will come after this line -->
    <div class="col-md">
      <h3 class="mx-3 my-3">Available Rides</h3>
        {% if horses.count %}
          {% for horse in horses.all %}
            <div class="card w-50 mx-2 my-3 shadow " style="background-color: #f6f6f6">
              <div class="card-content mx-2 my-3">
                <span class="card-title bg-success">
                  <p> {{ horse.name }} <p>
                  <form action="{% url 'assoc_horse' jockey.id horse.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-success">Add</button>
                  </form>
                </span>
              </div>
            </div> 
          {% endfor %}
        {% else %}
          <h5 class="mx-3 my-3">{{jockey.name}} has ridden all the horses in the database!</h5>
        {% endif %}
      </div>
    </div>

</div>

{% endblock %}